import { points } from "./cs";
import type { SiteCopy } from "./cs";

export const en: SiteCopy = {
  meta: {
    title: "Platit prosím – QR payments with no commission",
    description:
      "A payment terminal on your phone. Customers pay by bank transfer via a QR code or with Bitcoin. No commission, no server, your data stays on your devices.",
  },
  nav: {
    home: "Platit prosím, home",
    howItWorks: "How it works",
    team: "Employees",
    comparison: "Comparison",
    faq: "FAQ",
    openApp: "Open the app",
    switchLanguage: "Přepnout do češtiny",
    languageShort: "CS",
    toDark: "Dark appearance",
    toLight: "Light appearance",
  },
  hero: {
    eyebrow: "A payment terminal on your phone",
    titleBefore: "Accept payments ",
    titleAccent: "with no\u00a0commission",
    titleAfter: "",
    subtitle:
      "Customers scan a QR code and pay by bank transfer, or with Bitcoin over Lightning or Cashu. Your phone is the terminal. No server, no account: your data stays on your devices.",
    primaryCta: "Open the app",
    secondaryCta: "How it works",
    methods: ["Bank QR", "Lightning", "Cashu"],
    demoLabel: "Live demo",
    demoHint: "Type an amount and try a whole payment.",
  },
  how: {
    eyebrow: "How it works",
    title: "Three steps to getting paid",
    steps: points([
      {
        icon: "QrCode",
        title: "Enter the amount",
        body: "Tap the amount on the big keypad and press Request payment.",
      },
      {
        icon: "ScanLine",
        title: "The customer scans",
        body: "With their banking app for a transfer, or with a Bitcoin wallet.",
      },
      {
        icon: "CircleCheck",
        title: "Confirm",
        body: "The payment lands in the history, along with who took it.",
      },
    ]),
    bank: {
      title: "Bank",
      pill: "You confirm",
      body: "An SPD QR payment, which every Czech bank supports. The money goes straight to your account. Once you see it, tap Mark as paid.",
    },
    bitcoin: {
      title: "Bitcoin",
      pill: "Confirmed automatically",
      body: "Lightning and Cashu in a single QR code (BIP-321). The app detects the payment by itself and shows the confirmation right away.",
    },
  },
  history: {
    eyebrow: "History",
    title: "Every payment in one place",
    body: "Time, amount, method, status and who created the payment. Filter by employee and keep track of the day's takings.",
    points: points([
      {
        icon: "Users",
        title: "Filter by employee",
        body: "Who took how much today, in one tap.",
      },
      {
        icon: "Clock",
        title: "Daily total",
        body: "Takings in crowns, bank and Bitcoin payments together.",
      },
    ]),
  },
  team: {
    eyebrow: "Employees",
    title: "One till for the whole team",
    body: "Add an employee by scanning their Linky profile. They then log in with Linky on their own phone and can take payments.",
    points: points([
      {
        icon: "LogIn",
        title: "Log in with Linky",
        body: "No passwords and no new accounts. The employee just confirms the login in Linky.",
      },
      {
        icon: "Eye",
        title: "Everyone sees their part",
        body: "Employees see only their own payments. As the owner, you see everything.",
      },
      {
        icon: "KeyRound",
        title: "Bitcoin travels to you",
        body: "From the customer through the employee's phone to you, locked to your key. Only you can spend it.",
      },
    ]),
    flow: {
      label: "How a Bitcoin payment travels",
      customer: "Customer",
      employee: "Employee's phone",
      owner: "Owner",
      lock: "Locked to the owner's key",
    },
  },
  wallet: {
    eyebrow: "Wallet",
    title: "Bitcoin you actually hold",
    body: "The balance in sats and in crowns. Payments from employees arrive by themselves. Withdraw to a Lightning address, or send to Linky.",
    points: points([
      {
        icon: "Zap",
        title: "Withdraw over Lightning",
        body: "Enter a Lightning address or an invoice, check the fee and send.",
      },
      {
        icon: "Send",
        title: "Send to Linky",
        body: "Scan a Linky profile and send sats as a message.",
      },
    ]),
  },
  comparison: {
    eyebrow: "Comparison",
    title: "Why not a card terminal?",
    body: "A card terminal takes a percentage of every payment and needs its own hardware. Platit prosím needs neither.",
    cardTerminal: "Card terminal",
    platitProsim: "Platit prosím",
    rows: [
      {
        label: "Fee per payment",
        cardTerminal: "1–2 % of every payment",
        platitProsim: "CZK 0 by bank, a few sats for Bitcoin",
      },
      {
        label: "Hardware",
        cardTerminal: "A terminal to buy or rent",
        platitProsim: "The phone you already have",
      },
      {
        label: "Monthly fee",
        cardTerminal: "Often",
        platitProsim: "None",
      },
      {
        label: "Contract",
        cardTerminal: "With a bank or a provider",
        platitProsim: "None, just open the app",
      },
      {
        label: "Your data",
        cardTerminal: "With the provider",
        platitProsim: "Only on your devices",
      },
    ],
    note: "We don't take cards yet: the customer needs a banking app or a Bitcoin wallet.",
  },
  privacy: {
    eyebrow: "Privacy",
    title: "No account. No server. Your data.",
    body: "Platit prosím is local-first. Everything is stored on your phone and synced between your devices with end-to-end encryption through Evolu.",
    points: points([
      {
        icon: "User",
        title: "No sign-up",
        body: "No email, phone number or password. Open the app and start.",
      },
      {
        icon: "Smartphone",
        title: "No server",
        body: "There is no server your payments go through. We have nothing to lose or sell.",
      },
      {
        icon: "ShieldCheck",
        title: "Encrypted sync",
        body: "Devices sync end-to-end encrypted; the relay only sees ciphertext.",
      },
      {
        icon: "KeyRound",
        title: "Backup phrase",
        body: "24 words restore the shop, the history, the wallet and the employees on a new phone.",
      },
    ]),
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    items: [
      {
        question: "What does it cost?",
        answer:
          "The app is free and takes no cut of your payments. A bank transfer goes from the customer's account straight to yours with no fees. With Bitcoin, the Cashu mint charges small fees, usually a few sats: when you receive a payment, when an employee's phone forwards it to you, and when you withdraw.",
      },
      {
        question: "What does the customer need?",
        answer:
          "A banking app with QR payments (every Czech bank has them), or a Bitcoin wallet with Lightning or Cashu, such as Linky.",
      },
      {
        question: "How do I know a bank payment arrived?",
        answer:
          "Check it in your bank, for example by its notification. Every payment has its own variable symbol, so it is easy to find. Then tap Mark as paid.",
      },
      {
        question: "What if I lose my phone?",
        answer:
          "Enter the 24 words of your backup phrase on a new device and everything comes back: the shop, the history, the wallet and the employees.",
      },
      {
        question: "What are Lightning and Cashu?",
        answer:
          "Lightning is a network for fast and cheap Bitcoin payments. Cashu is digital cash backed by Bitcoin that is sent as a message. The app accepts both from one QR code.",
      },
      {
        question: "Does it work on a tablet or a computer?",
        answer:
          "Yes. Platit prosím is a web app that you install from the browser on a phone, a tablet or a computer.",
      },
      {
        question: "Is it open source?",
        answer: "Yes, all of the source code is on GitHub.",
      },
    ],
  },
  closing: {
    title: "Start taking payments today",
    body: "Open the app, enter your shop name and bank account. That's all it takes.",
  },
  footer: {
    tagline: "A payment terminal for Czech merchants.",
    linky: "Linky",
    github: "GitHub",
  },
  demo: {
    shopName: "Linden Café",
    tabs: {
      label: "Main sections",
      terminal: "Terminal",
      history: "History",
      team: "Team",
      wallet: "Wallet",
      settings: "Settings",
    },
    close: "Close",
    currency: "CZK",
    sat: "sat",
    amountCzk: (amount: string) => `${amount} CZK`,
    amountSats: (sats: string) => `${sats} sat`,
    amount: "Amount",
    decimal: "Decimal point",
    backspace: "Delete",
    requestPayment: "Request payment",
    payment: "Payment",
    method: "Payment method",
    bank: "Bank",
    bitcoin: "Bitcoin",
    lightning: "Lightning",
    cashu: "Cashu",
    bankQr: (amount: string) => `QR code to pay ${amount} by bank`,
    bitcoinQr: (amount: string) => `QR code to pay ${amount} with bitcoin`,
    variableSymbol: "Variable symbol",
    account: "Account",
    recipient: "Recipient",
    markPaid: "Mark as paid",
    cancelPayment: "Cancel payment",
    inBitcoin: "In bitcoin",
    rate: "Rate",
    rateValue: (rate: string) => `1 BTC = ${rate} CZK`,
    waiting: "Waiting for payment…",
    bitcoinHint: "Pay from any Lightning or Cashu wallet, such as Linky.",
    autoPay: "In the demo, the payment arrives by itself in a moment.",
    demoData: "Demo data, do not pay",
    paid: "Paid",
    newPayment: "New payment",
    status: { pending: "Pending", paid: "Paid", cancelled: "Cancelled" },
    historyEmptyTitle: "No payments yet",
    historyEmptyDescription: "Payments you create in the terminal appear here.",
    today: "Today",
    yesterday: "Yesterday",
    dayTotal: (amount: string) => `Received ${amount}`,
    me: "Me",
    employee: "Employee",
    everyone: "Everyone",
    filterTitle: "Who took the payment",
    paymentDetail: "Payment details",
    created: "Created",
    paidAt: "Paid",
    createdBy: "Created by",
    funds: "Funds",
    fundsInWallet: "In the wallet",
    addEmployee: "Add employee",
    addEmployeeDescription:
      "Scan the Linky profile QR code, or paste the npub.",
    linkyProfile: "Linky profile",
    linkyProfileHint: "An npub, nprofile or Linky profile link",
    linkyProfileInvalid: "This is not a Linky profile.",
    alreadyAdded: "This employee is already on the team.",
    scan: "Scan a profile QR code",
    scanner: "QR code scanner",
    scanHint: "Point the camera at a Linky profile QR code",
    profileMissing: "Linky profile without a name",
    name: "Name",
    nameHint: "Shown in the payment history.",
    addToTeam: "Add to the team",
    deviceWaiting: "Waiting for login",
    deviceLinked: "Linked",
    teamHint:
      "An employee logs in with Linky on their device, and it links by itself.",
    balance: "Balance",
    balanceCzk: (amount: string) => `≈ ${amount} CZK`,
    withdraw: "Withdraw over Lightning",
    sendToLinky: "Send to Linky",
    activity: "Activity",
    activityIn: (sats: string) => `+${sats} sat`,
    activityOut: (sats: string) => `−${sats} sat`,
    withdrawalLightning: "Lightning withdrawal",
    withdrawalLinky: "Sent to Linky",
    withdrawTarget: "Lightning address or invoice",
    withdrawTargetPlaceholder: "name@domain.com",
    withdrawTargetInvalid:
      "Enter a Lightning address or an invoice with an amount.",
    amountInvalid: "Enter a whole number of sats.",
    insufficient: "The wallet does not hold enough for this and the fee.",
    amountHint: (amount: string, sats: string) =>
      `≈ ${amount} CZK · ${sats} sat available`,
    available: (sats: string) => `${sats} sat available`,
    send: "Send",
    withdrawPaid: "Sent",
    withdrawPaidDetail: (sats: string) =>
      `${sats} sat went out over Lightning.`,
    linkySent: "Sent to Linky",
    linkySentDetail: (sats: string) =>
      `${sats} sat will arrive in the Linky chat.`,
    done: "Done",
    language: "Language",
    languageCs: "Čeština",
    languageEn: "English",
    theme: "Appearance",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    shop: "Shop",
    security: "Security",
    backupPhrase: "Backup phrase",
    backupNote:
      "These 24 words restore the shop, the history, the wallet and the employees.",
    backupWarning:
      "Never show the words to anyone. Whoever knows them can access the shop.",
    backupWords: "Backup phrase words",
    word: (position: number) => `Word ${position}`,
    restore: "Restore from backup",
    reset: "Reset this device",
    about: "About",
    mint: "Mint",
    terminalDemo: "Live terminal demo",
    historyDemo: "Payment history demo",
    teamDemo: "Employee management demo",
    walletDemo: "Wallet demo",
    settingsDemo: "Settings demo with the backup phrase",
  },
};
